### PR TITLE
Make <!environment|path=foobar  !> junk extract correctly environment…

### PR DESCRIPTION
**Pull request by Ducasse**
…|path=foobar

### CODE REVIEW

**Comment by kasperosterbye** [comment]
It seems like this issue should be handled in `MicInputfileBlock` rather than `MicEnvironmentBlock`. 
In `MicInputFile` this could be done as:
```Smalltalk
path: aPath
	arguments at: #'path' put: aPath trim "trim inserted".
```

The proposed solution in `MicInvironmentBlock` removes trailing blanks from any argument being the last. I cannot see any case where it would matter, but I see no reason to make the restriction that the last argument can not end in a blank, where as an argument in the middle of an argument list can.

**Comment by Ducasse** [comment]
Ths problem is <! jjlkjkljkjlkj lkj !> kjlkjklj
- So why it would make sense to have an argument ending with a blank?
- And right now the parser says that the argument is jjlkjkljkjlkj lkj !> kjlkjklj while it should be jjlkjkljkjlkj lkj
Notice that the space inside are kept. 

So just doing what you suggest does not work because the logic of termination was dull.

**Comment by Ducasse** [comment]
BTW I would also say that an argument in the middle should not end with a space. 
This is a recipe for bugs

**Comment by Ducasse** [comment]
BTW if we accept (as it is now) to have `<!environment .... !>` on the same line
then it should not break when we have `<!environment .... !>` blblblbl
May be environment should not allowed `<!environment .... !>` on the same line

**Comment by kasperosterbye** [comment]
See my comment in #521. I think this PR is a step in the right direction.

**Pull request merged**
