### PR TITLE
moved the presenter to its own package Microdown-RichTextPresenter

### PR DESCRIPTION
**Pull request by kasperosterbye**
I have not updated the baseline to include it. That is on purpose as it is still a little unclear where is should end up in the grander scheme of things.

### CODE REVIEW

**Comment by kasperosterbye** [comment]
@Ducasse - it seems like a massive change to what is being tested has taken place. A lot of failing test. Should I be worried? Should I help?

**Comment by kasperosterbye** [comment]
Massive amounts of tests broken - investigating.

**Comment by kasperosterbye** [comment]
Seems ready to roll @Ducasse. The huge number of errors was because the presenter was no longer loaded, but its tests were. Now the Presenter-Tests are in its own package `Microdown-RichTextPresenter-Tests`, and not part of the baseline.

**Comment by Ducasse** [comment]
Ok thanks I will redo a pass when I will integrate it because I liwk to have the tests loaded.

**Pull request merged**
