### PR TITLE
New 2.0.0 release for integration into Pharo

### PR DESCRIPTION
**Pull request by kasperosterbye**

### CODE REVIEW

**Comment by kasperosterbye** [comment]
Aha - I will try to find time to make sure all the release tests are satisfied - later this week I hope.

**Comment by Ducasse** [comment]
Else I will have a look this is just category renames I guess.
Just focusing on my deadline.

**Comment by Ducasse** [comment]
I will remove also beautiful comments

**Comment by kasperosterbye** [comment]
The two remaining fails are not in Microdown:
- #testNoLeadingOrTrailingSpacesInCategoryNames : `DTDEntity->#'private ' XMLEnumerationAttributeValidator->#'private ' BaselineOfXMLParser->#'prerequisites ' XMLHTTPZincRequest->#'private ' XMLHTTPDecompressingReadStreamAdapterFactory class->#'private ' SAX2Parser class->#'private '`
- #PRFigure PRMetadata PRParameters class StDebuggerCommand `PRFigure PRMetadata PRParameters class StDebuggerCommand`

I suggest to merge this one.
In the end only the packages `Microdown`, `Microdown-Tests`, and `Microdown-RichTextComposer` will be included

**Pull request merged**
