### PR TITLE
Zink based refs and resolver

### PR DESCRIPTION
**Pull request by kasperosterbye**
Do not merge!

This is a rather large refactoring of the Microdown-core classes (and everything else to accommodate those changes).
I am still in the process of cleaning it up, but I want to see the CI response.

Missing is examples and convenience methods, and a few classes need their docs updated.

The key change is that url resolution is done using the very well tested ZnUrl. Using Zink rather than the home made resolution made sure it works equally well for http as for files.

### CODE REVIEW

**Comment by Ducasse** [comment]
Ok. Thanks for doing this.

**Comment by Ducasse** [comment]
Let me know when this is ready.

**Comment by Ducasse** [comment]
Argh I just changed the inputfile. So I will revert my changes.

**Comment by Ducasse** [comment]
I do not know how to revert my changes :(

**Comment by Ducasse** [comment]
All my attempts failed so far. I will check if I can get some help. :(

**Comment by Ducasse** [comment]
Ok thanks to pablo

**Comment by kasperosterbye** [comment]
@Ducasse You can merge this - I believe it to be robust. 
I will continue to work on the documentation, convenience methods and perhaps tests if I find some odd corners.

**Comment by Ducasse** [comment]
Ok I will merge.

**Pull request merged**
