### PR TITLE
Document browser development

### PR DESCRIPTION
**Pull request by kasperosterbye**
Document browser will now handle links to microdown documents
I will write out a longer list of changes when I see if the tests run true

### CODE REVIEW

**Comment by kasperosterbye** [comment]
Ouch, this one looks like a github api resource error. I'll try again later, but it is really hard for me to debug.
If I am right that it is the credential issue it is in my view a Pharo-showstopper.

**Comment by kasperosterbye** [comment]
I need to clean up because my code was deleted due to too many open PR's

**Comment by Ducasse** [comment]
K.
Should I merge it?

**Comment by kasperosterbye** [comment]
Thanks Stef. No, I'll put a note here when it is ready.

**Comment by kasperosterbye** [comment]
@Ducasse 
It is ready for a merge. All tests green.
Please take a look at the changes in the core and richtext presenter as those will end up in Pharo eventually.

**Comment by Ducasse** [comment]
Ok I will have a look

**Comment by Ducasse** [comment]
Sounds ok for me.

**Pull request merged**
