### PR TITLE
216 package name microdown microdown rich text composer should be microdown rich text composer

### LINKED ISSUE #216: Package name Microdown-MicrodownRichTextComposer should be Microdown-RichTextComposer
To keep it consistent with the other packages.

There is an existing package name `Microdown-RichTextComposer` which only contains some extension methods.

Also - the test class `MicRichTextComposerTest` is in the same package as `MicRichTextComposer` which is against the conventions also.

### PR DESCRIPTION
**Pull request by kasperosterbye**
Fixes #216. I believe this will fix the package name issue. It does for me.

### CODE REVIEW

**Comment by Ducasse** [comment]
It was named like that because there was a MD-PillarRichTextComposer.

**Comment by kasperosterbye** [comment]
He he - well at least there was a good reason

**Comment by Ducasse** [comment]
Oops the changes broke the build.

**Comment by Ducasse** [comment]
I wonder if you changed the baseline?

**Comment by kasperosterbye** [comment]
Well spotted Stef - I did not change the baseline.

**Comment by kasperosterbye** [comment]
The baselines have been changed too now.

**Pull request merged**
