### PR TITLE
fix tests evaluator

### PR DESCRIPTION
**Pull request by leofrere**

### CODE REVIEW

**Comment by Ducasse** [comment]
One point per PR. Because I was touching the visitInputFile too.
So we will have a conflict.

**Comment by Ducasse** [comment]
So since two topics are mixed I cannot integrate one without the other.

**Comment by guillep** [comment]
Hi Stef, I don't understand, this PR does not touch `visitInputFile`. I only see that it modifies `MicCodeBlock`. Maybe you mean something else?

**Comment by Ducasse** [comment]
May be this is other PR.

**Pull request merged**
